#include "WeatherData.h"

//start original code
//implement WeatherData object that stores different country's values
WeatherData::WeatherData(std::string _timestamp,
                                double _AT,
                                double _BE,
                                double _BG,
                                double _CH,
                                double _CZ,
                                double _DE,
                                double _DK,
                                double _EE,
                                double _ES,
                                double _FI,
                                double _FR,
                                double _GB,
                                double _GR,
                                double _HR,
                                double _HU,
                                double _IE,
                                double _IT,
                                double _LT,
                                double _LU,
                                double _LV,
                                double _NL,
                                double _NO,
                                double _PL,
                                double _PT,
                                double _RO,
                                double _SE,
                                double _SI,
                                double _SK)
: timestamp(_timestamp),
    AT(_AT),
    BE(_BE),
    BG(_BG),
    CH(_CH),
    CZ(_CZ),
    DE(_DE),
    DK(_DK),
    EE(_EE),
    ES(_ES),
    FI(_FI),
    FR(_FR),
    GB(_GB),
    GR(_GR),
    HR(_HR),
    HU(_HU),
    IE(_IE),
    IT(_IT),
    LT(_LT),
    LU(_LU),
    LV(_LV),
    NL(_NL),
    NO(_NO),
    PL(_PL),
    PT(_PT),
    RO(_RO),
    SE(_SE),
    SI(_SI),
    SK(_SK)
{
    
}
//end original code